# Generated by Django 2.2.9 on 2020-02-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='institutionstaff',
            constraint=models.UniqueConstraint(fields=('user', 'institution'), name='unique_institution_staff_membership'),
        ),
    ]
