# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 11:13


from django.db import migrations

from entity.db.migrations import PopulateEntityIdsMigration


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20200324_0410'),
    ]

    operations = [
        PopulateEntityIdsMigration('staff', 'InstitutionStaff'),
        PopulateEntityIdsMigration('staff', 'FacultyStaff'),
        PopulateEntityIdsMigration('staff', 'IssuerStaff'),
        PopulateEntityIdsMigration('staff', 'BadgeclassStaff'),
    ]
