# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 20:26


import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway', '0007_fix_children_of_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pathway',
            managers=[
                ('cached', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pathwayelement',
            managers=[
                ('cached', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='pathway',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pathwayelement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pathwayelement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pathwayelement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
