# Generated by Django 2.2.7 on 2019-12-03 10:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathway', '0008_auto_20170711_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=254, populate_from='populate_slug', unique=True),
        ),
        migrations.AlterField(
            model_name='pathwayelement',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=254, populate_from='name', unique=True),
        ),
    ]
