target-version = "py312"
line-length = 120
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "migrations",
]

[lint]
select = ["ALL"]  # https://docs.astral.sh/ruff/rules/
ignore = [
    "ANN",  # Allow missing annotations
    "COM812",  # Incompatible with formatter
    "CPY001",  # Do not require copyright notices
    "D",  # Ignore docstring errors
    "E402",  # Allow imports not at top of file
    "EM",  # Allow messages directly in exceptions
    "PLR6301",  # Allow not using self in methods
    "PT",  # Not using pytest
    "RET504",  # Allow variable assignment before return
    "SIM108",  # Allow if-else block instead of ternary
    "SLF001",  # Allow private member access
    "TRY003",  # Specific messages for common exception classes
]
