# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0002_auto_20181023_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.CharField(max_length=512, verbose_name=b'welcomeMessage')),
                ('service_name', models.CharField(max_length=512, verbose_name=b'serviceName')),
                ('showPoweredByBadgr', models.CharField(max_length=512, verbose_name=b'showPoweredByBadgr')),
                ('showApiDocsLink', models.CharField(max_length=512, verbose_name=b'showApiDocsLink')),
                ('termsOfServiceLink', models.CharField(max_length=512, verbose_name=b'termsOfServiceLink')),
                ('privacyPolicyLink', models.CharField(max_length=512, verbose_name=b'privacyPolicyLink')),
                ('logo_small', models.FileField(upload_to=b'themes', verbose_name=b'logoImg.small')),
                ('logo_desktop', models.FileField(upload_to=b'themes', verbose_name=b'logoImg.desktop')),
                ('subdomain', models.CharField(max_length=56, unique=True, verbose_name=b'Sub domain')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='institution.Institution')),
            ],
        ),
    ]
