# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
