# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 09:58


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0002_theme_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='changed',
            new_name='changed_on',
        ),
    ]
