# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-15 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0003_auto_20190111_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='privacyPolicyLink',
            new_name='privacy_policy_link',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='showApiDocsLink',
            new_name='show_api_docs_link',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='showPoweredByBadgr',
            new_name='show_powered_by_badgr',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='termsOfServiceLink',
            new_name='terms_of_service_link',
        ),
    ]
