# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0004_auto_20190115_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='show_api_docs_link',
            field=models.BooleanField(default=False, verbose_name=b'showApiDocsLink'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='show_powered_by_badgr',
            field=models.BooleanField(default=False, verbose_name=b'showPoweredByBadgr'),
        ),
    ]
