# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('theming', '0005_auto_20190121_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='subdomain',
        ),
        migrations.AddField(
            model_name='theme',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='sites.Site'),
        ),
    ]
