# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0006_auto_20190122_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='privacy_policy_link',
            field=models.FileField(upload_to=b'themes', verbose_name=b'privacyPolicyLink'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='terms_of_service_link',
            field=models.FileField(upload_to=b'themes', verbose_name=b'termsOfServiceLink'),
        ),
    ]
