# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0007_auto_20190211_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='privacy_policy_link',
            field=models.CharField(max_length=512, verbose_name=b'privacyPolicyLink'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='terms_of_service_link',
            field=models.CharField(max_length=512, verbose_name=b'termsOfServiceLink'),
        ),
    ]
