# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 09:08


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20181116_0324'),
        ('theming', '0008_auto_20190219_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='badgr_app',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='mainsite.BadgrApp'),
        ),
    ]
