# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 09:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0010_auto_20190304_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='terms_and_conditions_template',
            field=models.CharField(max_length=512, null=True, verbose_name=b'Terms and conditions template'),
        ),
    ]
