# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0012_remove_theme_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='terms_and_conditions_template_en',
            field=models.CharField(max_length=512, null=True, verbose_name=b'Terms and conditions template english'),
        ),
    ]
