# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0013_theme_terms_and_conditions_template_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='terms_and_conditions_template',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name=b'Terms and conditions template'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='terms_and_conditions_template_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name=b'Terms and conditions template english'),
        ),
    ]
