# Generated by Django 2.2.7 on 2019-12-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0014_auto_20190705_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='badgr_app',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme', to='mainsite.BadgrApp'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logo_desktop',
            field=models.FileField(upload_to='themes', verbose_name='logoImg.desktop'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logo_small',
            field=models.FileField(upload_to='themes', verbose_name='logoImg.small'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='privacy_policy_link',
            field=models.CharField(max_length=512, verbose_name='privacyPolicyLink'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='service_name',
            field=models.CharField(max_length=512, verbose_name='serviceName'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='show_api_docs_link',
            field=models.BooleanField(default=False, verbose_name='showApiDocsLink'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='show_powered_by_badgr',
            field=models.BooleanField(default=False, verbose_name='showPoweredByBadgr'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='terms_and_conditions_template',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Terms and conditions template'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='terms_and_conditions_template_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Terms and conditions template english'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='terms_of_service_link',
            field=models.CharField(max_length=512, verbose_name='termsOfServiceLink'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='welcome_message',
            field=models.CharField(max_length=512, verbose_name='welcomeMessage'),
        ),
    ]
