# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0005_auto_20170514_1141'),
        ('badgeuser', '0013_auto_20170725_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgrAccessToken',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('oauth2_provider.accesstoken',),
        ),
    ]
