# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-01 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0015_badgeuser_badgrapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='lti_id',
            field=models.CharField(blank=True, default=None, help_text='LTI user id, unique per user', max_length=50, null=True, unique=True),
        ),
    ]
