# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-11 15:19


import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0016_auto_20180611_0802'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='termsversion',
            managers=[
                ('cached', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='termsversion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
