# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 12:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0016_badgeuser_lti_id'),
        ('badgeuser', '0018_termsversion_short_description'),
    ]

    operations = [
    ]
