# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 14:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0019_merge_20180710_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Non Issuer'), (2, 'Issuer'), (3, 'Issuer Admin')], default=1),
        ),
    ]
