# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0019_merge_20180710_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'default'), (2, 'issuer'), (3, 'issuer_creator')], default=1),
        ),
    ]
