# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0020_badgeuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgeuser',
            options={'permissions': (('view_issuer_tab', 'User can view Issuer tab in front end'),), 'verbose_name': 'badge user', 'verbose_name_plural': 'badge users'},
        ),
    ]
