# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0023_auto_20180811_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeuser',
            name='user_type',
        ),
    ]
