# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0025_badgeuserproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgeuserproxy',
            options={'verbose_name': 'Badge User Interface for SuperUser'},
        ),
    ]
