# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('badgeuser', '0027_auto_20180905_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='institution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
    ]
