# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0028_badgeuser_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgeuser',
            options={'permissions': (('view_issuer_tab', 'User can view Issuer tab in front end'), ('has_faculty_scope', 'User has faculty scope'), ('has_institution_scope', 'User has institution scope'), ('ui_issuer_add', 'User can add issuer in front end')), 'verbose_name': 'badge user', 'verbose_name_plural': 'badge users'},
        ),
    ]
