# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0029_auto_20181218_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsversion',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
