# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0030_termsversion_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsversion',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
