# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 15:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0031_termsversion_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsversion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='termsversion',
            name='short_description',
        ),
        migrations.AddField(
            model_name='termsversion',
            name='terms_and_conditions_template',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
