# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-27 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0031_termsversion_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Backend-staff member'),
        ),
    ]
