# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 12:54


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0033_auto_20190306_0308'),
        ('badgeuser', '0033_auto_20190408_0941'),
    ]

    operations = [
    ]
