# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 11:02


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('badgeuser', '0033_auto_20190408_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(default=None, max_length=254, null=True)),
                ('rank', models.PositiveIntegerField(default=None, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
