# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 11:13
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations

from entity.db.migrations import PopulateEntityIdsMigration


class Migration(migrations.Migration):

    dependencies = [
        # ('auth', '0009_group_entity_id'),
        ('badgeuser', '0033_auto_20190408_0941'),
    ]

    operations = [
        PopulateEntityIdsMigration('auth', 'Group'),
    ]
