# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0034_groupentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupentity',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', unique=True),
        ),
    ]
