# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 11:19


from django.db import migrations
from mainsite.utils import generate_entity_uri


def create_group_identity_ranks(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Group = apps.get_model('auth', 'Group')
    GroupEntity = apps.get_model('badgeuser', 'GroupEntity')
    for group in Group.objects.all():
        group_entity = GroupEntity()
        group_entity.group = group
        group_entity.entity_id = generate_entity_uri()
        group_entity.save()



class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0035_auto_20190614_0425'),
    ]

    operations = [
        migrations.RunPython(create_group_identity_ranks),
    ]
