# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 11:28


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0036_auto_20190614_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupentity',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entity_rank', to='auth.Group'),
        ),
    ]
