# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0034_merge_20190527_0554'),
        ('badgeuser', '0037_auto_20190614_0428'),
    ]

    operations = [
    ]
