# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0038_merge_20190618_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsversion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='termsversion',
            name='terms_and_conditions_template',
        ),
    ]
