# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 09:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0039_auto_20190705_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsversion',
            name='terms_and_conditions_template',
            field=models.CharField(max_length=512, null=True, verbose_name='Terms and conditions template'),
        ),
    ]
