# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0041_termsversion_accepted_terms_and_conditions_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termsversion',
            old_name='accepted_Terms_and_conditions_hash',
            new_name='accepted_terms_and_conditions_hash',
        ),
    ]
