# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 13:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0042_auto_20190705_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsagreement',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
