# Generated by Django 2.2.9 on 2020-02-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0045_auto_20191203_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeuser',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='badgeuser',
            name='institution',
        ),
    ]
