# Generated by Django 2.2.9 on 2020-03-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0046_auto_20200220_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeuser',
            name='entity_version',
        ),
    ]
