# Generated by Django 2.2.9 on 2020-03-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0047_remove_badgeuser_entity_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupentity',
            name='group',
        ),
        migrations.DeleteModel(
            name='BadgeUserProxy',
        ),
        migrations.DeleteModel(
            name='GroupEntity',
        ),
    ]
