# Generated by Django 2.2.9 on 2020-04-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0048_auto_20200306_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
