# Generated by Django 2.2.9 on 2020-06-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0022_auto_20200604_1258'),
        ('badgeuser', '0051_userprovisionment'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
    ]
