# Generated by Django 2.2.9 on 2020-06-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0054_userprovisionment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprovisionment',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
