# Generated by Django 2.2.9 on 2020-06-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0055_auto_20200615_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprovisionment',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
