# Generated by Django 2.2.9 on 2020-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0056_auto_20200615_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprovisionment',
            name='type',
            field=models.CharField(choices=[('Invitation', 'Invitation'), ('FirstAdminInvitation', 'FirstAdminInvitation')], max_length=254),
        ),
    ]
