# Generated by Django 2.2.13 on 2020-07-29 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0024_auto_20200615_1359'),
        ('badgeuser', '0059_populate_badgeuser_invited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('terms_type', models.CharField(choices=[('formal_badge', 'formal_badge'), ('informal_badge', 'informal_badge'), ('service_agreement_student', 'service_agreement_student'), ('service_agreement_employee', 'service_agreement_employee'), ('terms_of_service', 'terms_of_service')], default='terms_of_service', max_length=254)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='institution.Institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('language', models.CharField(choices=[('english', 'english'), ('dutch', 'dutch')], default='english', max_length=255)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badgeuser.Terms')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='termsagreement',
            options={},
        ),
        migrations.AddField(
            model_name='termsagreement',
            name='agreed_language',
            field=models.CharField(choices=[('english', 'english'), ('dutch', 'dutch')], default='english', max_length=255),
        ),
        migrations.AddField(
            model_name='termsagreement',
            name='agreed_version',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='termsagreement',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='TermsVersion',
        ),
        migrations.RemoveField(
            model_name='termsagreement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='termsagreement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='termsagreement',
            name='terms_version',
        ),
        migrations.RemoveField(
            model_name='termsagreement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='termsagreement',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='termsagreement',
            name='valid',
        ),
        migrations.AddField(
            model_name='termsagreement',
            name='terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='badgeuser.Terms'),
        ),
    ]
