# Generated by Django 2.2.13 on 2020-07-30 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0061_auto_20200729_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='institution.Institution'),
        ),
    ]
