# Generated by Django 2.2.13 on 2020-07-31 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0062_auto_20200730_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsurl',
            name='terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_urls', to='badgeuser.Terms'),
        ),
    ]
