# Generated by Django 2.2.13 on 2020-07-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0063_auto_20200731_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsurl',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('nl', 'nl')], default='en', max_length=255),
        ),
    ]
