# Generated by Django 2.2.13 on 2020-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0064_auto_20200731_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsagreement',
            name='agreed_language',
            field=models.CharField(choices=[('en', 'en'), ('nl', 'nl')], default='en', max_length=255),
        ),
    ]
