# Generated by Django 2.2.13 on 2020-08-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0068_auto_20200820_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsagreement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='termsagreement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
