# Generated by Django 2.2.13 on 2020-08-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0070_remove_termsagreement_agreed_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsagreement',
            name='entity_id',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
