# Generated by Django 2.2.13 on 2020-08-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0072_populate_termsagreement_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsagreement',
            name='entity_id',
            field=models.CharField(default=None, max_length=254, unique=True),
        ),
    ]
