# Generated by Django 2.2.14 on 2020-09-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0073_auto_20200820_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='badgeuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='last name'),
        ),
    ]
