# Generated by Django 2.2.14 on 2020-10-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0074_alter_user_columns_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='validated_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='validated name'),
        ),
    ]
