# Generated by Django 2.2.14 on 2020-10-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0075_badgeuser_validated_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeuser',
            name='validated_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='validated name'),
        ),
    ]
