# Generated by Django 2.2.24 on 2021-10-25 10:17

from django.db import migrations, models


def populate_allowed_urls(apps, schema_editor):
    ImportBadgeAllowedUrl = apps.get_model('badgeuser', 'ImportBadgeAllowedUrl')
    allowed_domains = ['https://api.eu.badgr.io', 'https://badgecollect.app/', 'https://badges.validana.io/']
    for domain in allowed_domains:
        import_badge_allowed_url = ImportBadgeAllowedUrl(url=domain)
        import_badge_allowed_url.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('badgeuser', '0077_studentaffiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBadgeAllowedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RunPython(populate_allowed_urls, reverse_code=noop)
    ]
