# Generated by Django 4.2.28 on 2026-02-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0078_importbadgeallowedurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportBadgeAllowedUrl',
        ),
    ]
