# Generated by Django 4.2.28 on 2026-02-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0079_delete_importbadgeallowedurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsagreement',
            name='agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
