# Generated by Django 4.2.28 on 2026-02-09 10:06

from django.db import migrations
from django.db.models import F


def populate_termsagreement_agreed_add(apps, schema_editor):
    TermsAgreement = apps.get_model('badgeuser', 'TermsAgreement')
    TermsAgreement.objects.filter(
        agreed=True,
        agreed_at__isnull=True
    ).update(agreed_at=F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0080_termsagreement_agreed_at'),
    ]

    operations = [
        migrations.RunPython(populate_termsagreement_agreed_add, migrations.RunPython.noop),
    ]
