# Generated by Django 5.2.13 on 2026-07-07 13:27

from django.db import migrations, models
from django.db.models import Max


def remove_invalid_provisionments(apps, schema_editor):
    UserProvisionment = apps.get_model('badgeuser', 'UserProvisionment')

    # For every unique (email, content_type, object_id) combination, keep the newest provisionment.
    unique_entities = (
        UserProvisionment.objects
        .values("email", "content_type_id", "object_id")
        .annotate(keep_id=Max("id"))
    )

    keep_ids = unique_entities.values_list("keep_id", flat=True)

    duplicate_provisionments = UserProvisionment.objects.exclude(id__in=keep_ids)
    duplicate_provisionments.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0081_populate_termsagreement_agreed_add'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(remove_invalid_provisionments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='userprovisionment',
            constraint=models.UniqueConstraint(fields=('email', 'content_type', 'object_id'), name='unique_email_content_type_object_id'),
        ),
    ]
