# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 23:36


from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0026_auto_20170726_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstance',
            name='issued_on',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
