# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0032_badgeclasstag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstance',
            name='recipient_type',
            field=models.CharField(choices=[('email', 'email'), ('openBadgeId', 'openBadgeId'), ('telephone', 'telephone'), ('url', 'url')], default='email', max_length=255),
        ),
    ]
