# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0033_auto_20171002_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='hashed',
            field=models.BooleanField(default=True),
        ),
    ]
