# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-01 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0034_badgeinstance_hashed'),
        ('issuer', '0035_issuer_badgrapp'),
    ]

    operations = [
    ]
