# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-13 18:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0036_merge_20171101_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstance',
            name='recipient_identifier',
            field=models.EmailField(db_index=True, max_length=512),
        ),
    ]
