# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-09 14:14


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0039_badgeclassextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeInstanceExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('badgeinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.BadgeInstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssuerExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Issuer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
