# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 15:13


import django.db.models.deletion
import issuer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0040_badgeinstanceextension_issuerextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeInstanceBakedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obi_version', models.CharField(max_length=254)),
                ('image', models.FileField(blank=True, upload_to=issuer.models._baked_badge_instance_filename_generator)),
                ('badgeinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.BadgeInstance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
