# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0041_badgeinstancebakedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstanceevidence',
            name='evidence_url',
            field=models.CharField(blank=True, default=None, max_length=2083, null=True),
        ),
    ]
