# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-14 16:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0042_auto_20180220_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstance',
            name='recipient_identifier',
            field=models.EmailField(db_index=True, max_length=768),
        ),
        migrations.AlterIndexTogether(
            name='badgeinstance',
            index_together=set([('recipient_identifier', 'badgeclass', 'revoked')]),
        ),
    ]
