# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-14 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0042_auto_20180220_1150'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='badgeinstance',
            index_together=set([('recipient_identifier', 'badgeclass', 'revoked')]),
        ),
    ]
