# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 16:13


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('issuer', '0043_auto_20180614_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='faculty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Faculty'),
        ),
    ]
