# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('issuer', '0043_auto_20180614_0949'),
        ('issuer', '0044_issuer_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstance',
            name='recipient_identifier',
            field=models.EmailField(db_index=True, max_length=768),
        ),
    ]
