# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 15:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0045_auto_20180925_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstance',
            name='recipient_type',
            field=models.CharField(choices=[('email', 'email'), ('openBadgeId', 'openBadgeId'), ('telephone', 'telephone'), ('url', 'url'), ('id', 'id')], default='id', max_length=255),
        ),
    ]
