# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0046_auto_20190613_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerstaff',
            name='is_signer',
            field=models.BooleanField(default=False),
        ),
    ]
