# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-11 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0044_issuer_faculty'),
        ('issuer', '0047_issuerstaff_is_signer'),
    ]

    operations = [
    ]
