# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-24 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0048_merge_20191011_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='signature',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
