# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0049_auto_20191024_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='identifier',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
