# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-18 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0051_badgeinstance_public_key_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='type',
            field=models.CharField(choices=[('formal', 'formal'), ('non-formal', 'non-formal')], default='formal', max_length=255),
        ),
    ]
