# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-26 10:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0052_badgeclass_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgeclass',
            old_name='type',
            new_name='category',
        ),
    ]
