# Generated by Django 2.2.9 on 2020-02-20 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200220_0538'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuer', '0057_remove_badgeclass_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='staff',
            field=models.ManyToManyField(through='staff.BadgeClassStaff', to=settings.AUTH_USER_MODEL),
        ),
    ]
