# Generated by Django 2.2.9 on 2020-02-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0058_badgeclass_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuer',
            name='staff',
        ),
        migrations.DeleteModel(
            name='IssuerStaff',
        ),
    ]
