# Generated by Django 2.2.9 on 2020-02-21 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0003_issuerstaff'),
        ('issuer', '0059_auto_20200221_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='staff',
            field=models.ManyToManyField(through='staff.IssuerStaff', to=settings.AUTH_USER_MODEL),
        ),
    ]
