# Generated by Django 2.2.9 on 2020-03-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0012_auto_20200304_0915'),
        ('issuer', '0061_remove_issuer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='issuer',
            unique_together={('name', 'faculty')},
        ),
    ]
