# Generated by Django 2.2.9 on 2020-03-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0063_auto_20200305_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeclass',
            name='entity_version',
        ),
        migrations.RemoveField(
            model_name='badgeinstance',
            name='entity_version',
        ),
        migrations.RemoveField(
            model_name='issuer',
            name='entity_version',
        ),
    ]
