# Generated by Django 2.2.9 on 2020-03-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0064_auto_20200305_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadgeInstanceEvidence',
        ),
    ]
