# Generated by Django 2.2.9 on 2020-03-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0065_delete_badgeinstanceevidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeinstance',
            name='narrative',
        ),
    ]
