# Generated by Django 2.2.9 on 2020-06-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0069_auto_20200511_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstance',
            name='salt',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=254, null=True),
        ),
    ]
