# Generated by Django 2.2.13 on 2020-10-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0073_auto_20200729_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstance',
            name='image',
            field=models.FileField(blank=True, db_index=True, null=True, upload_to='uploads/badges'),
        ),
    ]
