# Generated by Django 2.2.9 on 2020-12-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0075_description_multi_language_isssuer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuer',
            name='description',
        ),
    ]
