# Generated by Django 2.2.13 on 2021-01-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0076_remove_issuer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuer',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
