# Generated by Django 2.2.13 on 2021-01-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0077_auto_20210104_1507'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuer',
            unique_together=set(),
        ),
    ]
