# Generated by Django 2.2.14 on 2021-01-31 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0078_auto_20210106_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='narrative',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='BadgeInstanceEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('evidence_url', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('narrative', models.TextField(blank=True, default=None, null=True)),
                ('badgeinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.BadgeInstance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
