# Generated by Django 2.2.14 on 2021-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0079_auto_20210131_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuer',
            old_name='image',
            new_name='image_english',
        ),
        migrations.AddField(
            model_name='issuer',
            name='image_dutch',
            field=models.FileField(blank=True, null=True, upload_to='uploads/issuers'),
        ),
    ]
