# Generated by Django 2.2.14 on 2021-02-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0082_auto_20210218_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuer',
            old_name='url',
            new_name='url_english',
        ),
        migrations.AddField(
            model_name='issuer',
            name='url_dutch',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
