# Generated by Django 2.2.14 on 2021-03-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0080_badgeclass_is_private'),
        ('issuer', '0083_auto_20210223_1844'),
    ]

    operations = [
    ]
