# Generated by Django 2.2.14 on 2021-03-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0084_merge_20210301_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstanceevidence',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='badgeinstanceevidence',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
