# Generated by Django 2.2.14 on 2021-03-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0085_auto_20210302_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='include_evidence',
            field=models.BooleanField(default=False),
        ),
    ]
