# Generated by Django 2.2.18 on 2021-03-22 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0086_badgeinstance_include_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Faculty'),
        ),
    ]
