# Generated by Django 2.2.14 on 2021-03-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0087_auto_20210322_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='award_type',
            field=models.CharField(choices=[('email', 'email'), ('openBadgeId', 'openBadgeId'), ('telephone', 'telephone'), ('url', 'url'), ('id', 'id')], default='requested', max_length=255),
        ),
    ]
