# Generated by Django 2.2.14 on 2021-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0088_badgeinstance_award_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstance',
            name='award_type',
            field=models.CharField(choices=[('requested', 'requested'), ('direct_award', 'direct_award')], default='requested', max_length=255),
        ),
    ]
