# Generated by Django 2.2.18 on 2021-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0042_auto_20210512_1538'),
        ('issuer', '0090_badgeinstance_direct_award_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='award_allowed_institutions',
            field=models.ManyToManyField(blank=True, help_text='Allow awards to this institutions', to='institution.Institution'),
        ),
        migrations.AlterField(
            model_name='badgeclass',
            name='formal',
            field=models.BooleanField(default=False),
        ),
    ]
