# Generated by Django 2.2.18 on 2021-06-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0091_auto_20210512_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='evidence_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='narrative_required',
            field=models.BooleanField(default=False),
        ),
    ]
