# Generated by Django 2.2.24 on 2021-09-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0094_badgeinstancecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstancecollection',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
