# Generated by Django 2.2.26 on 2022-03-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0096_badgeclass_award_non_validated_name_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='evidence_student_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='narrative_student_required',
            field=models.BooleanField(default=False),
        ),
    ]
