# Generated by Django 2.2.26 on 2022-04-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0097_auto_20220315_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='is_micro_credentials',
            field=models.BooleanField(default=False),
        ),
    ]
