# Generated by Django 2.2.26 on 2022-04-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0098_badgeclass_is_micro_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='direct_awarding_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
