# Generated by Django 2.2.26 on 2022-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0099_badgeclass_direct_awarding_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclassalignment',
            name='target_url',
            field=models.CharField(blank=True, default=None, max_length=2083, null=True),
        ),
    ]
