# Generated by Django 3.2.16 on 2023-03-28 06:58

import json

from django.db import migrations


def migrate_education_program_identifiers_badge_class_extension(apps, schema_editor):
    BadgeClassExtension = apps.get_model('issuer', 'BadgeClassExtension')
    BadgeInstanceExtension = apps.get_model('issuer', 'BadgeInstanceExtension')
    for instance in [BadgeClassExtension, BadgeInstanceExtension]:
        for ext in instance.objects.filter(name="extensions:EducationProgramIdentifierExtension").all():
            obj = json.loads(ext.original_json)
            obj['EducationProgramIdentifier'] = [obj['EducationProgramIdentifier']]
            ext.original_json = json.dumps(obj)
            ext.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('issuer', '0101_badgeclass_self_enrollment_disabled'),
    ]

    operations = [
        migrations.RunPython(migrate_education_program_identifiers_badge_class_extension, reverse_code=noop)
    ]
