# Generated by Django 3.2.24 on 2024-04-08 13:31

from django.db import migrations, models


def migrate_badge_class_type(apps, schema_editor):
    BadgeClass = apps.get_model('issuer', 'BadgeClass')
    for badge_class in BadgeClass.objects.all():
        if badge_class.is_micro_credentials:
            badge_class.badge_class_type = 'micro_credential'
        elif badge_class.formal:
            badge_class.badge_class_type = 'regular'
        else:
            badge_class.badge_class_type = 'extra_curricular'
        badge_class.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('issuer', '0102_multiple_educationProgramIdentifiers_badgeClassExtension'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='badge_class_type',
            field=models.CharField(blank=True,
                                   choices=[('micro_credential', 'micro_credential'), ('regular', 'regular'),
                                            ('extra_curricular', 'extra_curricular')], default='regular',
                                   max_length=254, null=True),
        ),
        migrations.RunPython(migrate_badge_class_type, reverse_code=noop)
    ]
