# Generated by Django 3.2.24 on 2024-04-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0103_badgeclass_badge_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclass',
            name='badge_class_type',
            field=models.CharField(choices=[('micro_credential', 'micro_credential'), ('regular', 'regular'), ('extra_curricular', 'extra_curricular')], default='regular', max_length=254),
        ),
    ]
