# Generated by Django 3.2.24 on 2024-04-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0104_alter_badgeclass_badge_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='participation',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
