# Generated by Django 3.2.24 on 2024-04-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0105_badgeclass_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='assessment_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='assessment_supervised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='assessment_type',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='grade_achieved_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='quality_assurance_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='quality_assurance_name',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='quality_assurance_url',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='stackable',
            field=models.BooleanField(default=False),
        ),
    ]
