# Generated by Django 3.2.24 on 2024-04-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0054_badgeclasstag'),
        ('issuer', '0106_auto_20240412_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='tags',
            field=models.ManyToManyField(blank=True, to='institution.BadgeClassTag'),
        ),
        migrations.DeleteModel(
            name='BadgeClassTag',
        ),
    ]
