# Generated by Django 3.2.24 on 2024-04-16 14:12

from django.db import migrations
from django.db.models import Q
from django.db.models.functions.text import Trim


def migrate_badge_class_criteria_url(apps, schema_editor):
    BadgeClass = apps.get_model('issuer', 'BadgeClass')
    badge_classes = list(
        BadgeClass.objects.alias(trimmed_criteria_text=Trim('criteria_text'))
        .filter(Q(trimmed_criteria_text='') | Q(trimmed_criteria_text__isnull=True))
        .filter(criteria_url__isnull=False).all())
    for badge_class in badge_classes:
        badge_class.criteria_text = badge_class.criteria_url
        badge_class.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('issuer', '0107_auto_20240412_1521'),
    ]

    operations = [
        migrations.RunPython(migrate_badge_class_criteria_url, reverse_code=noop)
    ]
