# Generated by Django 3.2.24 on 2024-04-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0108_badge_class_criteria_url_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeclass',
            name='criteria_url',
        ),
    ]
