# Generated by Django 3.2.24 on 2024-04-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0109_remove_badgeclass_criteria_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclass',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/badges'),
        ),
    ]
