# Generated by Django 3.2.24 on 2024-04-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0110_alter_badgeclass_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='grade_achieved',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
