# Generated by Django 3.2.24 on 2024-04-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0111_badgeinstance_grade_achieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='include_grade_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
