# Generated by Django 3.2.24 on 2024-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0113_alter_badgeclass_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclass',
            name='participation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
