# Generated by Django 3.2.24 on 2024-07-09 12:49

from django.db import migrations

from issuer.micro_credentials_constants import micro_credentials_framework, micro_credentials_framework_mbo


def migrate_micro_credentials_badge_class_alignment(apps, schema_editor):
    BadgeClassAlignment = apps.get_model('issuer', 'BadgeClassAlignment')
    mc_alignments = BadgeClassAlignment.objects \
        .filter(target_name__icontains="Microcredentials voor Professionals") \
        .all()
    for alignment in mc_alignments:
        bc = alignment.badgeclass
        is_mbo = bc.issuer.faculty.institution.institution_type == "MBO"
        mc_framework = micro_credentials_framework_mbo if is_mbo else micro_credentials_framework
        bc.quality_assurance_name = mc_framework.get("name")
        bc.quality_assurance_description = mc_framework.get("description")
        bc.quality_assurance_url = mc_framework.get("url")
        bc.save()
        alignment.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('issuer', '0114_alter_badgeclass_participation'),
    ]

    operations = [
        migrations.RunPython(migrate_micro_credentials_badge_class_alignment, reverse_code=noop)
    ]
