# Generated by Django 3.2.24 on 2024-07-09 12:49

from django.db import migrations


def migrate_micro_credentials_badge_class_alignment(apps, schema_editor):
    BadgeClassAlignment = apps.get_model('issuer', 'BadgeClassAlignment')
    mc_alignments = BadgeClassAlignment.object.filter(name__icontains="Microcredentials voor Professionals").all()
    for alignment in mc_alignments:
        bc = alignment.badgeclass
        is_mbo = bc.issuer.faculty.institution.institution_type == "MBO"
        bc.quality_assurance_name = bc.target_name
        bc.quality_assurance_description = bc.target_description
        bc.quality_assurance_url = "https://npuls.nl/microcredentials-mbo/" if is_mbo else "https://www.versnellingsplan.nl/en/Kennisbank/pilot-microcredentials-2/"
        bc.save()
        alignment.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('issuer', '0114_alter_badgeclass_participation'),
    ]

    operations = [
        migrations.RunPython(migrate_micro_credentials_badge_class_alignment, reverse_code=noop)
    ]
