# Generated by Django 4.2.17 on 2025-03-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0116_migrate_studyLoad_to_timeExtension'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='badgeinstance',
            new_name='issuer_badg_recipie_6a2cd8_idx',
            old_fields=('recipient_identifier', 'badgeclass', 'revoked'),
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='eqf_nlqf_level_verified',
            field=models.BooleanField(default=False),
        ),
    ]
