# Generated by Django 3.2.25 on 2024-09-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0116_migrate_studyLoad_to_timeExtension'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='badgeinstance',
            index_together={('recipient_identifier', 'badgeclass', 'revoked')},
        ),
    ]
