# Generated by Django 4.2.22 on 2025-10-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0117_rename_badgeinstance_recipient_identifier_badgeclass_revoked_issuer_badg_recipie_6a2cd8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeinstance',
            name='public',
        ),
        migrations.RemoveField(
            model_name='badgeinstancecollection',
            name='public',
        ),
    ]
