# Generated by Django 4.2.28 on 2026-02-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0117_rename_badgeinstance_recipient_identifier_badgeclass_revoked_issuer_badg_recipie_6a2cd8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
