# Generated by Django 4.2.28 on 2026-02-19 10:54

from django.db import migrations, transaction


def populate_recipient_name(apps, schema_editor):
    BadgeInstance = apps.get_model("issuer", "BadgeInstance")

    BATCH_SIZE = 3000
    total = BadgeInstance.objects.filter(recipient_name__isnull=True).count()

    print(f"Starting to populate recipient_name for {total} BadgeInstances...")

    badges_to_update = []
    processed_count = 0
    updated_count = 0

    for badge in BadgeInstance.objects.filter(recipient_name__isnull=True).select_related("user").iterator(chunk_size=BATCH_SIZE):
        validated_name = getattr(badge.user, "validated_name", None) if badge.user else None
        if validated_name:
            badge.recipient_name = validated_name
            badges_to_update.append(badge)
            updated_count += 1

        processed_count += 1

        # process in batches
        if processed_count % BATCH_SIZE == 0:
            with transaction.atomic():
                BadgeInstance.objects.bulk_update(badges_to_update, ['recipient_name'])
            print(f"Processed {processed_count} / {total} badges, updated {updated_count} badges...")
            badges_to_update = []

    # update any remaining badges
    if badges_to_update:
        with transaction.atomic():
            BadgeInstance.objects.bulk_update(badges_to_update, ['recipient_name'])
        print(f"Processed all {total} badges.")

    print("Finished populating recipient_name.")

class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0118_badgeinstance_recipient_name'),
    ]

    operations = [
        migrations.RunPython(populate_recipient_name),
    ]
