# Generated by Django 4.2.28 on 2026-02-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0118_normalize_public_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
