# Generated by Django 5.2.13 on 2026-04-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0119_populate_recipient_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadgeInstanceBakedImage',
        ),
    ]
