# Generated by Django 5.2.13 on 2026-06-04 08:11

from django.db import migrations
from issuer.micro_credentials_constants import micro_credentials_framework


def update_quality_assurance_description_and_url(apps, _):
    BadgeClass = apps.get_model('issuer', 'BadgeClass')

    hbo_wo_micro_credentials = BadgeClass.objects.filter(
        is_micro_credentials=True,
        badge_class_type="micro_credential",
        quality_assurance_name__icontains="Kwaliteitskader Microcredentials voor Professionals HBO en WO",
        issuer__faculty__institution__institution_type__in=["HBO", "WO"],
    )

    description = micro_credentials_framework.get('description')

    hbo_wo_micro_credentials.update(
        quality_assurance_url="https://npuls.nl/doorbouwen-aan-microcredentials",
        quality_assurance_description=description,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0120_delete_badgeinstancebakedimage'),
    ]

    operations = [
        migrations.RunPython(update_quality_assurance_description_and_url, reverse_code=migrations.RunPython.noop),
    ]
