# Generated by Django 4.2.22 on 2025-10-02 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('issuer', '0119_populate_recipient_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RemoveField(
                    model_name='badgeinstance',
                    name='public',
                ),
                migrations.RemoveField(
                    model_name='badgeinstancecollection',
                    name='public',
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='badgeinstance',
                    name='public',
                ),
                migrations.RemoveField(
                    model_name='badgeinstancecollection',
                    name='public',
                ),
            ],
        ),
    ]
