# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 12:06


import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20181023_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='entity_id',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, max_length=255, null=True, populate_from=b'name'),
        ),
    ]
