# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 12:08
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_populate_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='entity_id',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, max_length=255, null=True, populate_from=b'name', unique=True),
        ),
    ]
