# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 17:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_auto_20190419_0508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together=set([('name', 'institution')]),
        ),
    ]
