# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_auto_20190421_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='entity_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='entity_id',
            field=models.CharField(default=None, max_length=254, unique=True),
        ),
    ]
