# Generated by Django 2.2.9 on 2020-02-20 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200220_0538'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0007_auto_20190422_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='staff',
            field=models.ManyToManyField(through='staff.FacultyStaff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='staff',
            field=models.ManyToManyField(through='staff.InstitutionStaff', to=settings.AUTH_USER_MODEL),
        ),
    ]
