# Generated by Django 2.2.9 on 2020-03-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_auto_20200220_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
