# Generated by Django 2.2.9 on 2020-03-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0011_populate_institution_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='entity_id',
            field=models.CharField(default=None, max_length=254, unique=True),
        ),
    ]
