# Generated by Django 2.2.9 on 2020-03-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0012_auto_20200304_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='entity_version',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='entity_version',
        ),
    ]
