# Generated by Django 2.2.9 on 2020-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0013_auto_20200305_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
