# Generated by Django 2.2.9 on 2020-03-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0017_auto_20200326_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
