# Generated by Django 2.2.9 on 2020-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0018_faculty_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='brin',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='grading_table',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/institution'),
        ),
    ]
