# Generated by Django 2.2.9 on 2020-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0019_auto_20200327_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='identifier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
