# Generated by Django 2.2.9 on 2020-06-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0022_auto_20200604_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
