# Generated by Django 2.2.9 on 2020-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0023_auto_20200615_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='identifier',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
