# Generated by Django 2.2.13 on 2020-08-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0026_auto_20200804_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='identifier',
            field=models.CharField(help_text='This is the schac_home', max_length=255, null=True, unique=True),
        ),
    ]
