# Generated by Django 2.2.13 on 2020-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0027_auto_20200804_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='identifier',
            field=models.CharField(help_text='This is the schac_home, must be set when creating', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(help_text='Must be set when creating', max_length=255, unique=True),
        ),
    ]
