# Generated by Django 2.2.13 on 2020-12-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0030_auto_20201214_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='grondslag_formeel',
            field=models.CharField(blank=True, choices=[('uitvoering_overeenkomst', 'uitvoering_overeenkomst'), ('gerechtvaardigd_belang', 'gerechtvaardigd_belang'), ('wettelijke_verplichting', 'wettelijke_verplichting'), (None, None)], default='uitvoering_overeenkomst', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='grondslag_informeel',
            field=models.CharField(blank=True, choices=[('uitvoering_overeenkomst', 'uitvoering_overeenkomst'), ('gerechtvaardigd_belang', 'gerechtvaardigd_belang'), ('wettelijke_verplichting', 'wettelijke_verplichting'), (None, None)], default='uitvoering_overeenkomst', max_length=254, null=True),
        ),
    ]
