# Generated by Django 2.2.13 on 2021-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0032_auto_20210119_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
