# Generated by Django 2.2.13 on 2021-01-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0033_faculty_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('WO', 'WO'), ('HBO', 'HBO'), ('MBO', 'MBO')], max_length=254, null=True),
        ),
    ]
