# Generated by Django 2.2.14 on 2021-02-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0034_institution_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='default_language',
            field=models.CharField(choices=[('nl-NL', 'nl-NL'), ('en-US', 'en-US')], default='nl-NL', max_length=254),
        ),
    ]
