# Generated by Django 2.2.14 on 2021-02-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0038_auto_20210224_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name_english',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
