# Generated by Django 2.2.18 on 2021-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0040_institution_direct_awarding_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='award_allow_all_institutions',
            field=models.BooleanField(blank=True, default=False, help_text='Allow awards to all institutions', null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='award_allowed_institutions',
            field=models.ManyToManyField(blank=True, help_text='Allow awards to this institutions', to='institution.Institution'),
        ),
    ]
