
# Generated by Django 2.2.18 on 2021-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0041_auto_20210509_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='award_allow_all_institutions',
            field=models.BooleanField(default=False, help_text='Allow awards to all institutions'),
        ),
    ]
