# Generated by Django 2.2.24 on 2021-10-18 10:53

from django.db import migrations, models


def populate_institution_public_institution(apps, schema_editor):
    Institution = apps.get_model('institution', 'Institution')
    for institution in Institution.objects.all():
        institution.public_institution = True
        institution.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('institution', '0042_auto_20210512_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='public_institution',
            field=models.BooleanField(default=True, help_text='Set to false to exclude from the catalog'),
        ),
        migrations.RunPython(populate_institution_public_institution, reverse_code=noop)
    ]
