# Generated by Django 2.2.26 on 2022-01-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0043_institution_public_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='lti_enabled',
            field=models.BooleanField(default=False, help_text='Set to true to enable LTI for this institution'),
        ),
    ]
