# Generated by Django 2.2.26 on 2022-02-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0044_institution_lti_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='on_behalf_of',
            field=models.BooleanField(default=False),
        ),
    ]
