# Generated by Django 2.2.26 on 2022-03-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0045_faculty_on_behalf_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='on_behalf_of_display_name',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='on_behalf_of_url',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
