# Generated by Django 2.2.26 on 2022-04-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0046_auto_20220315_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='alternative_identifier',
            field=models.CharField(blank=True, default=None, help_text='An alternative schac_home for the Pilot microcredentials(e.g. institutionX.tempguestidp.edubadges.nl', max_length=255, null=True),
        ),
    ]
