# Generated by Django 2.2.26 on 2022-04-13 06:49

from django.db import migrations, models


def migrate_institutions_default_language(apps, _):
    Institution = apps.get_model('institution', 'Institution')
    for institution in Institution.objects.all():
        institution.default_language = 'nl_NL' if institution.default_language == 'nl-NL' else 'en_EN'
        institution.save()


class Migration(migrations.Migration):
    dependencies = [
        ('institution', '0047_institution_alternative_identifier'),
    ]

    operations = [
        migrations.RunPython(migrate_institutions_default_language, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='institution',
            name='alternative_identifier',
            field=models.CharField(blank=True, default=None,
                                   help_text='An alternative schac_home for the Pilot microcredentials (e.g. institutionX.tempguestidp.edubadges.nl)',
                                   max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='default_language',
            field=models.CharField(choices=[('nl_NL', 'nl_NL'), ('en_EN', 'en_EN')], default='nl_NL', max_length=254),
        ),
    ]
