# Generated by Django 3.2.16 on 2023-02-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0049_institution_eppn_reg_exp_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='linkedin_org_identifier',
            field=models.CharField(blank=True, default=None, help_text='LinkedIn organisation identifier', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='eppn_reg_exp_format',
            field=models.CharField(blank=True, default=None, help_text='A regular expression which defines the EPPN of an institution (e.g. .*@tempguestidp.edubadges.nl). For multiple logical OR use the following format:(.*@university.org|.*@university-sub.org)', max_length=255, null=True),
        ),
    ]
