# Generated by Django 3.2.18 on 2023-05-01 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0050_auto_20230206_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='manage_client_id',
            field=models.CharField(blank=True, default=None, help_text='OpenConext client_id for token introspection. The secret is stored in Manage', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='sis_default_user',
            field=models.ForeignKey(blank=True, default=None, help_text='The edubadges user that will be used for Direct Awards through theSIS API. Must be an administrator of this institution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sis_institution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='sis_integration_enabled',
            field=models.BooleanField(default=False, help_text='Set to true to enable SIS integration for this institution'),
        ),
    ]
