# Generated by Django 3.2.20 on 2024-01-09 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0051_auto_20230501_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='ob3_ssi_agent_enabled',
            field=models.BooleanField(default=False, help_text='Set to true to enable OB3 integration for this institution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='sis_default_user',
            field=models.ForeignKey(blank=True, default=None, help_text='The edubadges user that will be used for Direct Awards through the SIS API. Must be an administrator of this institution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sis_institution', to=settings.AUTH_USER_MODEL),
        ),
    ]
