# Generated by Django 3.2.24 on 2024-04-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0052_auto_20240109_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='micro_credentials_enabled',
            field=models.BooleanField(default=False, help_text='Set to true to enable Micro-crdentials for this institution'),
        ),
    ]
