# Generated by Django 3.2.24 on 2024-02-26 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('institution', '0052_alter_institution_sis_default_user'),
        ('institution', '0052_auto_20240109_1351'),
    ]

    operations = [
    ]
