# Generated by Django 3.2.24 on 2024-06-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0055_micro_credentials_enabled_for_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclasstag',
            name='archived',
            field=models.BooleanField(default=False, help_text='Set to true to disable this tag from being selectable'),
        ),
    ]
