# Generated by Django 3.2.24 on 2024-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0056_badgeclasstag_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='country_code',
            field=models.CharField(choices=[('NL', 'NL'), ('EN', 'EN')], default='NL', max_length=254),
        ),
    ]
