# Generated by Django 3.2.25 on 2024-10-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0057_institution_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('WO', 'WO'), ('HBO', 'HBO'), ('MBO', 'MBO'), ('HBO/MBO', 'HBO/MBO')], max_length=254, null=True),
        ),
    ]
