# Generated by Django 3.2.25 on 2024-08-14 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('institution', '0053_merge_20240226_1350'),
        ('institution', '0057_institution_country_code'),
    ]

    operations = [
    ]
