# Generated by Django 3.2.25 on 2024-10-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0058_alter_institution_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(blank=True, choices=[('HBO', 'HBO'), ('MBO', 'MBO')], max_length=254, null=True),
        ),
    ]
