# Generated by Django 3.2.25 on 2024-10-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0059_faculty_faculty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='image_dutch',
            field=models.FileField(blank=True, null=True, upload_to='uploads/faculties'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='image_english',
            field=models.FileField(blank=True, null=True, upload_to='uploads/faculties'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='linkedin_org_identifier',
            field=models.CharField(blank=True, default=None, help_text='LinkedIn organisation identifier', max_length=255, null=True),
        ),
    ]
