# Generated by Django 3.2.25 on 2024-10-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0060_auto_20241015_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='virtual_organization_allowed',
            field=models.BooleanField(default=False, help_text='Set to true to enable Virtual Organizations for this institution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='micro_credentials_enabled',
            field=models.BooleanField(default=False, help_text='Set to true to enable Micro-credentials for this institution'),
        ),
    ]
