# Generated by Django 3.2.25 on 2024-10-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0062_auto_20241015_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='virtual_organization_allowed',
            field=models.BooleanField(default=True, help_text='Set to true to enable Virtual Organizations for this institution'),
        ),
    ]
