# Generated by Django 3.2.25 on 2024-11-13 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('institution', '0058_merge_20240814_0929'),
        ('institution', '0065_default_test_visibility_type_surf_institution'),
    ]

    operations = [
    ]
