# Generated by Django 3.2.25 on 2024-12-18 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('institution', '0066_institution_email'),
        ('institution', '0066_merge_20241113_1458'),
    ]

    operations = [
    ]
