# Generated by Django 4.2.27 on 2026-02-04 07:41

from django.db import migrations


def populate_institution_email(apps, schema_editor):
    Institution = apps.get_model("institution", "Institution")
    InstitutionStaff = apps.get_model("institution", "InstitutionStaff")

    for institution in Institution.objects.filter(email__isnull=True):
        # Find oldest active admin
        staff = (
            InstitutionStaff.objects.filter(
                institution=institution,
                may_administrate_users=True,
                user__is_active=True,
            )
            .select_related("user")
            .order_by("user__date_joined")
            .first()
        )

        if staff and staff.user and staff.user.email:
            institution.email = staff.user.email
            institution.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0066_institution_email'),
    ]

    operations = [
    ]
