# Generated by Django 4.2.28 on 2026-02-09 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0008_auto_20200526_1536'),
        ('institution', '0068_populate_institution_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='staff',
            field=models.ManyToManyField(related_name='+', through='staff.InstitutionStaff', to=settings.AUTH_USER_MODEL),
        ),
    ]
