# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-11 13:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externaltools', '0002_externaltooluseractivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltool',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='externaltool',
            name='requires_user_activation',
            field=models.BooleanField(default=True),
        ),
    ]
