# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-11 13:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externaltools', '0003_auto_20180411_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltool',
            name='xml_config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
