# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 10:27


import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externaltools', '0004_auto_20180411_0653'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='externaltool',
            managers=[
                ('cached', django.db.models.manager.Manager()),
            ],
        ),
    ]
