# Generated by Django 2.2.24 on 2021-11-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti13', '0002_lticourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticourse',
            name='entity_id',
            field=models.CharField(default=None, max_length=254, unique=True),
        ),
    ]
