# Generated by Django 2.2.24 on 2021-11-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti13', '0003_lticourse_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticourse',
            name='tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lti13.LtiTool'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltitool',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
