SURF_INSTITUTION_NAME = 'SURF'
EDU_BADGES_FACULTY_NAME = 'eduBadges'
EDU_BADGES_ISSUER_NAME = 'Team edubadges'

BADGE_CLASS_INTRODUCTION_TO_PSYCHOLOGY = 'Introduction to Psychology'
BADGE_CLASS_COGNITIVE_PSYCHOLOGY = 'Cognitive Psychology'
BADGE_CLASS_PSYCHOMETRICS = 'Psychometrics'
BADGE_CLASS_GROUP_DYNAMICS = 'Group Dynamics'
