# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 20:26


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0009_auto_20170509_1937'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipientgroup',
            managers=[
                ('cached', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='recipientprofile',
            managers=[
                ('cached', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='recipientgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
