# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-01 07:25


import django.utils.timezone
import lti_edu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuer', '0042_auto_20180220_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default=b'', max_length=400, null=True)),
                ('consumer_key', models.CharField(default=lti_edu.models.get_uuid, max_length=50)),
                ('shared_secret', models.CharField(default=lti_edu.models.get_uuid, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LtiPayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentsEnrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_consent_given', models.DateTimeField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, default=b'', max_length=400, null=True)),
                ('last_name', models.CharField(blank=True, default=b'', max_length=400, null=True)),
                ('assertion_slug', models.CharField(blank=True, default=b'', max_length=150, null=True)),
                ('date_awarded', models.DateTimeField(blank=True, default=None, null=True)),
                ('badge_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_students', to='issuer.BadgeClass')),
            ],
        ),
    ]
