# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-01 12:25


import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0042_auto_20180220_1150'),
        ('lti_edu', '0002_lticlient_issuer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLinkBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('resource_link', models.CharField(max_length=255, unique=True)),
                ('badge_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_resource_link', to='issuer.BadgeClass')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_resource_link', to='issuer.Issuer')),
            ],
        ),
    ]
