# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0004_lticlient_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsenrolled',
            name='edu_id',
            field=models.CharField(blank=True, default=b'', max_length=400, null=True),
        ),
    ]
