# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ims', '0002_ltiapp_ltitenant'),
        ('lti_edu', '0006_studentsenrolled_denied'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiBadgeUserTennant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lti_user_id', models.CharField(max_length=512)),
                ('badge_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lti_tennant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.LTITenant')),
            ],
        ),
    ]
