# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0045_auto_20180925_0534'),
        ('lti_edu', '0007_ltibadgeusertennant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeClassLtiContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_id', models.CharField(max_length=512)),
                ('badge_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.BadgeClass')),
            ],
        ),
        migrations.AddField(
            model_name='ltibadgeusertennant',
            name='time_out',
            field=models.DateTimeField(null=True),
        ),
    ]
