# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 11:13
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations

from entity.db.migrations import PopulateEntityIdsMigration


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0007_auto_20190422_0745'),
    ]

    operations = [
        PopulateEntityIdsMigration('lti_edu', 'LtiClient'),
    ]
