# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0008_populate_lti_client_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticlient',
            name='entity_id',
            field=models.CharField(default=None, max_length=254, unique=True),
        ),
    ]
