# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 12:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0008_auto_20190326_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltibadgeusertennant',
            name='time_out',
        ),
        migrations.AddField(
            model_name='ltibadgeusertennant',
            name='token',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
