# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0009_auto_20190326_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltibadgeusertennant',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
