# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 10:37


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0045_auto_20180925_0534'),
        ('lti_edu', '0010_ltibadgeusertennant_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclasslticontext',
            name='badge_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_context', to='issuer.BadgeClass'),
        ),
        migrations.AlterUniqueTogether(
            name='badgeclasslticontext',
            unique_together=set([('badge_class', 'context_id')]),
        ),
    ]
