# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0012_auto_20190415_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercurrentcontextid',
            name='context_id',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
