# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 09:27


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0014_ltibadgeusertennant_current_lti_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsenrolled',
            name='badge_class_lti_context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lti_edu.BadgeClassLtiContext'),
        ),
    ]
