# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-22 09:48


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lti_edu', '0015_studentsenrolled_badge_class_lti_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsenrolled',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
