# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-22 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0017_populate_studentsenrolled_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsenrolled',
            name='edu_id',
        ),
        migrations.RemoveField(
            model_name='studentsenrolled',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentsenrolled',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentsenrolled',
            name='last_name',
        ),
    ]
