# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-23 12:07


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0018_auto_20191022_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsenrolled',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
