# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-12 09:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0022_remove_studentsenrolled_assertion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltibadgeusertennant',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
    ]
