# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-12 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0019_auto_20191023_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltibadgeusertennant',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
    ]
