# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-17 20:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0021_populate_studentsenrolled_badgeinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsenrolled',
            name='assertion_slug',
        ),
    ]
