# Generated by Django 2.2.7 on 2019-12-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0022_remove_studentsenrolled_assertion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticlient',
            name='name',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
