# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 11:13


from django.db import migrations

from entity.db.migrations import PopulateEntityIdsMigration


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0024_studentsenrolled_entity_id'),
    ]

    operations = [
        PopulateEntityIdsMigration('lti_edu', 'StudentsEnrolled'),
    ]
