# Generated by Django 2.2.8 on 2019-12-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0025_populate_entity_id_enrollments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsenrolled',
            name='entity_id',
            field=models.CharField(default=None, max_length=254, unique=True),
        ),
    ]
