# Generated by Django 2.2.24 on 2021-11-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0026_auto_20191225_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsenrolled',
            name='deny_reason',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
