# Generated by Django 2.2.24 on 2021-11-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0027_studentsenrolled_deny_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsenrolled',
            name='deny_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
