# Generated by Django 2.2.24 on 2021-11-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0028_auto_20211107_1107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badgeclasslticontext',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='badgeclasslticontext',
            name='badge_class',
        ),
        migrations.RemoveField(
            model_name='ltibadgeusertennant',
            name='badge_user',
        ),
        migrations.RemoveField(
            model_name='lticlient',
            name='issuer',
        ),
        migrations.DeleteModel(
            name='LtiPayload',
        ),
        migrations.RemoveField(
            model_name='resourcelinkbadge',
            name='badge_class',
        ),
        migrations.RemoveField(
            model_name='resourcelinkbadge',
            name='issuer',
        ),
        migrations.AlterUniqueTogether(
            name='usercurrentcontextid',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercurrentcontextid',
            name='badge_user',
        ),
        migrations.RemoveField(
            model_name='studentsenrolled',
            name='badge_class_lti_context',
        ),
        migrations.DeleteModel(
            name='BadgeClassLtiContext',
        ),
        migrations.DeleteModel(
            name='LtiBadgeUserTennant',
        ),
        migrations.DeleteModel(
            name='LtiClient',
        ),
        migrations.DeleteModel(
            name='ResourceLinkBadge',
        ),
        migrations.DeleteModel(
            name='UserCurrentContextId',
        ),
    ]
