# Generated by Django 2.2.26 on 2022-03-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0029_auto_20211115_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsenrolled',
            name='evidence_url',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='studentsenrolled',
            name='narrative',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
