# Generated by Django 4.2.17 on 2025-03-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_edu', '0030_auto_20220315_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsenrolled',
            name='deny_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
