# Generated by Django 4.2.28 on 2026-02-14 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255, unique=True)),
                (
                    'device_type',
                    models.CharField(blank=True, help_text='Type of device (iOS/Android)', max_length=50, null=True),
                ),
                ('device_model', models.CharField(blank=True, help_text='Device model', max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, help_text='App version', max_length=50, null=True)),
                (
                    'os_version',
                    models.CharField(blank=True, help_text='Operating system version', max_length=50, null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile Device',
                'verbose_name_plural': 'Mobile Devices',
            },
        ),
        migrations.CreateModel(
            name='MobileAPIRequestLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(help_text='API endpoint called', max_length=255)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('status_code', models.IntegerField(help_text='HTTP status code')),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                (
                    'device',
                    models.ForeignKey(
                        blank=True,
                        help_text='Related mobile device',
                        null=True,
                        on_delete=models.SET_NULL,
                        to='mobile_api.mobiledevice',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Mobile API Request Log',
                'verbose_name_plural': 'Mobile API Request Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['device_id'], name='mobile_api_m_device__9a73f9_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['created_at'], name='mobile_api_m_created_136c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['last_seen'], name='mobile_api_m_last_se_9a2b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileapirequestlog',
            index=models.Index(fields=['timestamp'], name='mobile_api_m_timesta_2a0b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileapirequestlog',
            index=models.Index(fields=['endpoint'], name='mobile_api_m_endpoin_3a0b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileapirequestlog',
            index=models.Index(fields=['method'], name='mobile_api_m_method_3a0b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileapirequestlog',
            index=models.Index(fields=['status_code'], name='mobile_api_m_status__3a0b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileapirequestlog',
            index=models.Index(fields=['device'], name='mobile_api_m_device__3a0b7e_idx'),
        ),
    ]
