# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-19 13:34


from django.db import migrations, models
import mainsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20171004_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinfo',
            name='allowed_scopes',
            field=models.TextField(validators=[mainsite.models.DefinedScopesValidator()]),
        ),
    ]
