# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 04:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20171019_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgrapp',
            name='public_pages_redirect',
            field=models.URLField(null=True),
        ),
    ]
