# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 18:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_badgrapp_public_pages_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgrapp',
            name='oauth_authorization_redirect',
            field=models.URLField(null=True),
        ),
    ]
