# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_badgrapp_oauth_authorization_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinfo',
            name='trust_email_verification',
            field=models.BooleanField(default=False),
        ),
    ]
