# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_applicationinfo_trust_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgrapp',
            name='use_auth_code_exchange',
            field=models.BooleanField(default=False),
        ),
    ]
