# Generated by Django 2.2.18 on 2021-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_auto_20191203_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgrapp',
            name='is_demo_environment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
