# Generated by Django 2.2.18 on 2021-04-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_badgrapp_is_demo_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgrapp',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
