# Generated by Django 3.2.24 on 2024-07-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_systemnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
