# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 20:26


import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0003_backpackcollection_assertions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='backpackcollection',
            managers=[
                ('cached', django.db.models.manager.Manager()),
            ],
        ),
    ]
