# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backpack', '0005_auto_20171025_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpackcollectionbadgeinstance',
            name='badgeuser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
