# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 15:37


from django.db import migrations


def populate_backpackcollectionbadgeinstance_user(apps, schema_editor):
    BackpackCollectionBadgeInstance = apps.get_model('backpack', 'BackpackCollectionBadgeInstance')
    for collect in BackpackCollectionBadgeInstance.objects.all():
        collect.badgeuser_id = collect.collection.created_by_id
        collect.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0006_backpackcollectionbadgeinstance_badgeuser'),
    ]

    operations = [
        migrations.RunPython(populate_backpackcollectionbadgeinstance_user, reverse_code=noop)
    ]
