# Generated by Django 2.2.9 on 2020-03-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0011_auto_20191203_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backpackcollection',
            name='entity_version',
        ),
    ]
