# Generated by Django 2.2.9 on 2020-05-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0014_auto_20200421_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backpackcollectionbadgeinstance',
            name='badgeinstance',
        ),
        migrations.RemoveField(
            model_name='backpackcollectionbadgeinstance',
            name='badgeuser',
        ),
        migrations.RemoveField(
            model_name='backpackcollectionbadgeinstance',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='backpackcollectionshare',
            name='collection',
        ),
        migrations.DeleteModel(
            name='BackpackCollection',
        ),
        migrations.DeleteModel(
            name='BackpackCollectionBadgeInstance',
        ),
        migrations.DeleteModel(
            name='BackpackCollectionShare',
        ),
    ]
