# Generated by Django 2.2.24 on 2021-10-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0016_importedassertion'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedassertion',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importedassertion',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
