# Generated by Django 2.2.24 on 2021-10-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0017_auto_20211008_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedassertion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
