# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-11 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuer', '0046_auto_20190613_0820'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_private_key', models.TextField()),
                ('initialization_vector', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('associated_data', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('public_key_pem', models.TextField()),
                ('time_created', models.DateTimeField()),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Issuer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SymmetricKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('n', models.IntegerField()),
                ('r', models.IntegerField()),
                ('p', models.IntegerField()),
                ('current', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('may_sign_assertions', 'User may sign assertions'),),
            },
        ),
        migrations.AddField(
            model_name='privatekey',
            name='public_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signing.PublicKey'),
        ),
        migrations.AddField(
            model_name='privatekey',
            name='symmetric_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signing.SymmetricKey'),
        ),
        migrations.AddField(
            model_name='privatekey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
