# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-29 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatekey',
            name='user',
        ),
    ]
