# Generated by Django 2.2.7 on 2019-12-03 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0003_auto_20191113_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertiontimestamp',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatekey',
            name='public_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='signing.PublicKey'),
        ),
        migrations.AlterField(
            model_name='privatekey',
            name='symmetric_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='signing.SymmetricKey'),
        ),
        migrations.AlterField(
            model_name='publickeyissuer',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issuer.Issuer'),
        ),
        migrations.AlterField(
            model_name='publickeyissuer',
            name='public_key',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='signing.PublicKey'),
        ),
        migrations.AlterField(
            model_name='symmetrickey',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
