# Generated by Django 2.2.9 on 2020-03-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0004_auto_20191203_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publickey',
            name='entity_version',
        ),
        migrations.RemoveField(
            model_name='publickeyissuer',
            name='entity_version',
        ),
    ]
