# Generated by Django 2.2.9 on 2020-03-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0005_auto_20200305_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symmetrickey',
            options={},
        ),
    ]
