# Generated by Django 2.2.14 on 2021-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0002_directaward_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='directaward',
            name='acceptance',
            field=models.CharField(choices=[('Unaccepted', 'Unaccepted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Unaccepted', max_length=254),
        ),
    ]
