# Generated by Django 2.2.14 on 2021-03-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0003_directaward_acceptance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directaward',
            name='recipient',
        ),
    ]
