# Generated by Django 2.2.14 on 2021-03-29 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuer', '0089_auto_20210329_1519'),
        ('directaward', '0005_remove_directaward_acceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectAwardBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('initial_total', models.IntegerField()),
                ('badgeclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.BadgeClass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='directaward',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directaward.DirectAwardBundle'),
        ),
    ]
