# Generated by Django 2.2.14 on 2021-04-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0006_auto_20210329_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='directaward',
            name='status',
            field=models.CharField(choices=[('Unaccepted', 'Unaccepted'), ('Revoked', 'Revoked'), ('Rejected', 'Rejected')], default='Unaccepted', max_length=254),
        ),
    ]
