# Generated by Django 2.2.26 on 2022-01-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0009_auto_20210908_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='directawardbundle',
            name='lti_import',
            field=models.BooleanField(default=False),
        ),
    ]
