# Generated by Django 3.2.18 on 2023-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0012_auto_20230329_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='directawardbundle',
            name='sis_client_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='directawardbundle',
            name='sis_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directawardbundle',
            name='sis_user_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='directaward',
            name='status',
            field=models.CharField(choices=[('Unaccepted', 'Unaccepted'), ('Revoked', 'Revoked'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled')], default='Unaccepted', max_length=254),
        ),
    ]
