# Generated by Django 3.2.18 on 2023-05-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0013_auto_20230501_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='directaward',
            name='resend_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
