# Generated by Django 3.2.20 on 2023-08-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0014_directaward_resend_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='directaward',
            name='delete_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='directaward',
            name='status',
            field=models.CharField(choices=[('Unaccepted', 'Unaccepted'), ('Revoked', 'Revoked'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled'), ('Deleted', 'Deleted')], default='Unaccepted', max_length=254),
        ),
    ]
