# Generated by Django 3.2.24 on 2024-04-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0015_auto_20230815_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='directaward',
            name='grade_achieved',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
