# Generated by Django 3.2.25 on 2024-11-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0017_directawardaudittrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='directawardbundle',
            name='identifier_type',
            field=models.CharField(choices=[('eppn', 'eppn'), ('email', 'email')], default='eppn', max_length=254),
        ),
        migrations.AlterField(
            model_name='directaward',
            name='eppn',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
