# Generated by Django 4.2.17 on 2025-04-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0018_auto_20241104_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directaward',
            name='warning_email_send',
        ),
        migrations.AddField(
            model_name='directaward',
            name='reminders',
            field=models.IntegerField(default=0),
        ),
    ]
