# Generated by Django 4.2.17 on 2025-04-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0019_remove_directaward_warning_email_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directaward',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
