# Generated by Django 4.2.20 on 2025-04-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directaward", "0020_directaward_expiration_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="directawardaudittrail",
            old_name="direct_award_entity_id",
            new_name="badgeclass_id",
        ),
        migrations.AddField(
            model_name="directawardaudittrail",
            name="direct_award_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
