# Generated by Django 4.2.20 on 2025-05-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0021_rename_direct_award_entity_id_directawardaudittrail_badgeclass_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directawardbundle',
            name='direct_award_expired_count',
            field=models.IntegerField(default=0),
        ),
    ]
