# Generated by Django 4.2.20 on 2025-05-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0022_directawardbundle_direct_award_expired_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='directawardbundle',
            name='direct_award_removed_count',
            field=models.IntegerField(default=0),
        ),
    ]
