# Generated by Django 4.2.27 on 2026-01-19 11:57

from django.db import migrations, models


def forwards_populate_audit_trail_fks(apps, schema_editor):
    DirectAwardAuditTrail = apps.get_model('directaward', 'DirectAwardAuditTrail')
    DirectAward = apps.get_model('directaward', 'DirectAward')
    BadgeClass = apps.get_model('issuer', 'BadgeClass')

    for audit in DirectAwardAuditTrail.objects.all().iterator():
        if audit.direct_award_entity_id and not audit.direct_award:
            audit.direct_award = (
                DirectAward.objects
                .filter(entity_id=audit.direct_award_entity_id)
                .first()
            )

        if audit.badgeclass_entity_id and not audit.badgeclass:
            audit.badgeclass = (
                BadgeClass.objects
                .filter(entity_id=audit.badgeclass_entity_id)
                .first()
            )

        audit.save(update_fields=['direct_award', 'badgeclass'])


def backwards_restore_entity_ids(apps, schema_editor):
    DirectAwardAuditTrail = apps.get_model('directaward', 'DirectAwardAuditTrail')

    for audit in DirectAwardAuditTrail.objects.all().iterator():
        if audit.direct_award and not audit.direct_award_entity_id:
            audit.direct_award_entity_id = audit.direct_award.entity_id

        if audit.badgeclass and not audit.badgeclass_entity_id:
            audit.badgeclass_entity_id = audit.badgeclass.entity_id

        audit.save(update_fields=[
            'direct_award_entity_id',
            'badgeclass_entity_id',
        ])

class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0023_directawardbundle_direct_award_removed_count'),
        ('issuer',
         '0117_rename_badgeinstance_recipient_identifier_badgeclass_revoked_issuer_badg_recipie_6a2cd8_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directawardaudittrail',
            old_name='badgeclass_id',
            new_name='badgeclass_entity_id',
        ),
        migrations.RenameField(
            model_name='directawardaudittrail',
            old_name='direct_award_id',
            new_name='direct_award_entity_id',
        ),
        migrations.AddField(
            model_name='directawardaudittrail',
            name='badgeclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to='issuer.badgeclass'),
        ),
        migrations.AddField(
            model_name='directawardaudittrail',
            name='direct_award',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to='directaward.directaward'),
        ),
        migrations.RunPython(
            forwards_populate_audit_trail_fks,
            backwards_restore_entity_ids,
        ),
        migrations.RemoveField(
            model_name='directawardaudittrail',
            name='badgeclass_entity_id',
        ),
        migrations.RemoveField(
            model_name='directawardaudittrail',
            name='direct_award_entity_id',
        ),
    ]
