# Generated by Django 4.2.28 on 2026-02-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0024_directawardaudittrail_refactor_badgeclass_and_directaward_relations_and_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='directaward',
            name='recipient_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directaward',
            name='recipient_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
