# Generated by Django 4.2.29 on 2026-04-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directaward', '0025_directaward_recipient_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directawardbundle',
            name='lti_import',
        ),
    ]
