name: Docker Image CI

permissions:
  id-token: write
  attestations: write

on:
  push:
    branches: ["feature/ewi"]
    tags:
      - ewi-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: cr.surf.nl
          username: ${{ secrets.CR_SURF_USERNAME }}
          password: ${{ secrets.CR_SURF_PASSWORD }}

      - name: Build and push Docker image latest-test
        id: push-latest-test
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/k8s.Dockerfile
          push: true
          tags: cr.surf.nl/edubadges-edubadges/edubadges/edubadges-server:latest-test

      - name: Build and push Docker image latest
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        id: push-latest
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/k8s.Dockerfile
          push: true
          # tags are nested on cr.surf.nl
          # e.g. docker pull cr.surf.nl/edubadges-edubadges/edubadges/edubadges-server
          tags: cr.surf.nl/edubadges-edubadges/edubadges/edubadges-server:latest

      - name: Get tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image tag version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: push-tag
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/k8s.Dockerfile
          push: true
          # tags are nested on cr.surf.nl
          # e.g. docker pull cr.surf.nl/edubadges-edubadges/edubadges/edubadges-server
          tags: cr.surf.nl/edubadges-edubadges/edubadges/edubadges-server:${{ steps.previoustag.outputs.tag }}

      - name: Generate artifact attestation for latest
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: cr.surf.nl/edubadges-edubadges/edubadges/edubadges-server
          subject-digest: ${{ steps.push-latest.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation for tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: cr.surf.nl/edubadges-edubadges/edubadges/edubadges-server
          subject-digest: ${{ steps.push-tag.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation for latest-test
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: cr.surf.nl/edubadges-edubadges/edubadges/edubadges-server
          subject-digest: ${{ steps.push-latest-test.outputs.digest }}
          push-to-registry: true
