name: Docker Image CI for Tag

permissions:
  id-token: write
  attestations: write

on:
  push:
    tags:
      - e*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for github-action-get-previous-tag

      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next minor version
        id: semver
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Log in to SURF harbor
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: cr.surf.nl
          username: ${{ secrets.CR_SURF_USERNAME }}
          password: ${{ secrets.CR_SURF_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/k8s.Dockerfile
          push: true
          # tags are nested on cr.surf.nl
          # e.g. docker pull cr.surf.nl/edubadges-edubadges/edubadges/edubadges-server
          tags: cr.surf.nl/edubadges-edubadges/edubadges/edubadges-server:${{ steps.semver.outputs.patch }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: cr.surf.nl/edubadges-edubadges/edubadges/edubadges-server
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
